Bp 39 implement email scheduler
gdsc-konkuk/platform-core pull request #15
Opened 2024-08-02 09:48 UTC by ekgns33

### 작업 내역
- 예약 취소 기능
- 이메일 예약
- 서버 부팅 시 예약 작업 로드
- 이메일 예약 수정 시 예약 취소 후 새로운 예약 

### 작업이 아닌것

2024-08-02 16:22 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
> +  public void scheduleSyncTask(Object emailTask, long delay) {
여기서 실행할 작업을 Runnable로 정의합니다. Callable과 Runnable둘다 사용가능한데 리턴받을 데이터가 없다고 생각해서 Runnable로 만들었습니다.

Runnable을 스케줄러에 등록하면 ScheduledFuture 객체가 반환되는데요 이거를 메모리에 들고있어야 취소가 가능해집니다!
그래서 TaskInMemoryRepository < ConcurrentHashMap을 담고있는 클래스에서 이를 관리하게되요.

여기서 생각해본 것은 저 자료구조의 future객체를 동시에 접근하는 경우가 뭐가 있을까? 였어요.

해당 자료구조에 접근하는 상황을 나열해보면
1. 새로 예약해서 작업을 추가하고 future을 저장 = put
2. 예약을 수정해서 작업을 취소하고 future을 삭제 = remove
3. 예약을 취소해서 작업을 취소하고 future을 삭제 = remove

그런데 수정과 취소 모두에서 remove를 접근하기 때문에 lock을 걸기로 회의에서 정했어유

2024-08-02 16:24 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/global/exceptions/GlobalErrorCode.java
> +  SCHEDULED_TASK_NOT_AVAILABLE("해당 작업은 유효하지 않습니다.", "[ERROR] : 인메모리 저장소에 예약된 작업을 찾을 수 없음");
SCHEDULED_TASK_NOT_FOUND에서 Not Available로 바꾸고 메세지를 "작업이 유효하지 않다." 로 수정했어요.
다만 서버에 남는 로그에는 인메모리 저장소에서 작업을 못 찾은 것으로 설정했어요

2024-08-02 16:26 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
> +    log.info("EmailTaskScheduler initialized");
서버가 시작될때 데이터베이스에서 아직 완료되지 않은 Task들을 가져와서 모두 스케줄하는 함수 입니다.
스프링 빈 등록이 완료된 후에 진행되요!
서버가 죽었을 때를 생각해서 작성했습니다

2024-08-04 04:48 UTC, goldentrash requested changes
고생하셨습니다! 몇가지 질문 남겨뒀어욥

2024-08-04 04:48 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
> +          emailService.markAsCompleted(email.getId());
runnable이 중간에 실패할 경우에는 어떻게 되나요?
e.g., `emailService.markAsCompleted(email.getId());` 수행 (성공)
`taskInMemoryRepository.removeTask(String.valueOf(email.getId()));` 실패

2024-08-04 04:48 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailScheduleService.java
> +@RequiredArgsConstructor
`@Transactional`한 다른 Service와 상호작용이 진행되니 `@Transactional` annotation이 필요하진 않을까요?

2024-08-04 04:48 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/controller/email/EmailController.java
> +    emailScheduleService.cancelEmailTask(emailId);
`emailScheduleService`와 `emailService` 중 어느것을 사용해야 할지가 모호한것 같아요. 두 서비스를 하나로 합치는건 어떨까요?

가령, email **조회**에는 `emailService`를 사용해야 하는데, email **삭제**에는 `emailScheduleService`를 사용해야 하는게 무언가 위화감이 드네요. 현 상황에서 **모든 이메일은 예약 메일**이기 때문에 더욱 헷갈리는것 같아요.
email **수정**시에도 내용 수정은 `emailService`에서 수행하고 이를 `emailScheduleService`가 호출(사용)하는 방향으로 보이는데, 후에 유지보수시에 다른 개발자가 코드를 리딩하며 `emailService.update`를 호출하는 실수를 범할 위험이 커 보여요

2024-08-04 04:48 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/global/scheduler/SchedulerConfig.java
> +package gdsc.konkuk.platformcore.global.scheduler;
`global/configs`로 파일을 옮기는 것에 대해 어떻게 생각하시나요? `TaskNotFoundException`이 `global/exceptions` 아래에 위치한 것과 같은 맥락입니다

2024-08-04 07:43 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
> +          emailService.markAsCompleted(email.getId());
에러핸들링을 해줘야합니당. 근데 실패케이스들에 대해 어떻게 처리할건지 안정해서 아직 try catch가 없어유

2024-08-04 07:44 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/controller/email/EmailController.java
> +    emailScheduleService.cancelEmailTask(emailId);
emailScheduleService는 파사드에 가까운데 합치는것도 좋아보여유

2024-08-04 10:34 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
> +      emailTaskRepository.save(emailTask);
아 개발과정에서 한 작업에 여러 레포지토리를 수정하여 save 로 커밋을 했었는데 지금은 빼도 될것 같네요

2024-08-04 10:40 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailScheduleService.java
> +@RequiredArgsConstructor
맞숨돠 수정할게용

2024-08-04 13:04 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/controller/email/EmailController.java
> +    emailScheduleService.cancelEmailTask(emailId);
Naming 변경으로 결정

2024-08-05 06:36 UTC, goldentrash approved these changes
고생하셨습니다!!!

2024-08-05 06:36 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
> +            taskInMemoryRepository.removeTask(String.valueOf(id));
`taskInMemoryRepository.removeTask(String.valuOf(id))`를 `finally` block으로 옮기는 것에 대해서 어떻게 생각하시나요?

2024-08-05 07:13 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
> +            taskInMemoryRepository.removeTask(String.valueOf(id));
아 finally가 있었군요. 반영하겠슴돠

2024-08-05 07:18 UTC, merged