Feat: include receiver name into mail registration
gdsc-konkuk/platform-core pull request #31
Opened 2024-08-19 11:33 UTC by goldentrash

- 이메일 예약 중 `email` 값은 받아오지만, `name` 값이 request에 누락되어있던 문제 해결
- 이메일 내용 중 `{이름}`을 수신자의 이름으로 치환하도록 변경
- 이메일 통합테스트 중, 확률적으로 fail하던 테스트가 언제나 pass하도록 변경
- 이메일 테스트 중, windows OS에서 허용되지 않는 restdocs id를 windows OS 호환되도록 수정

2024-08-19 11:45 UTC, ekgns33 requested changes
고생하셨어유

2024-08-19 11:45 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailReceiverInfo.java
> +@Setter
Setter를 열어둘 필요가 있을까요? VO라는점을 생각해보는게 어때요

2024-08-19 11:45 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
> +      String emailContent = emailDetails.getContent().replaceAll("\\{이름}", to.getName());
컨텐츠 수정을 담당하는 메소드를 분리하는게 어때요? 테스트코드도 필요해 보여요.
{이름}` 이라는 패턴 외에도 사용할 수 있도록 패턴을 입력받도록 수정하고 `\\{이름}`은 consts 파일로 옮겨서 상수로 사용할까요?

2024-08-20 13:00 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailReceiverInfo.java
> +@Setter
`EmailReceiverInfo`는 DTO입니다. VO인 `EmailReceiver`는 확인해보니 Setter를 열어두지 않았더군욥

2024-08-20 13:00 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
> +      String emailContent = emailDetails.getContent().replaceAll("\\{이름}", to.getName());
`{이름}`을 상수로 분리하고 메서드 분리해 보았습니다. 다만, 다른 패턴에 대해서는 기획적으로 논의된 부분이 없어 추가하지 않았습니다

2024-08-21 02:36 UTC, ekgns33 approved these changes
고생하셨어여 머지해두겠숨돠!

2024-08-21 02:36 UTC, merged