[Feat] member management
gdsc-konkuk/platform-core pull request #54
Opened 2024-11-21 15:50 UTC by goldentrash

### 한 일

- 회원 정보 수정 API 구현
- 회원 탈퇴를 현 로그인 유저를 삭제하는것이 아닌, 운영진이 특정 유저를 삭제하는 방식으로 변경
- 회원 목록 조회

### ? 발생 예상 지점

```java
  @DeleteMapping("/{batch}/{memberId}")
  public ResponseEntity<SuccessResponse> withdraw(
        @PathVariable String batch, @PathVariable Long memberId
  ) {
    memberService.withdraw(memberId);
    return ResponseEntity.noContent().build();
  }
```

**Q**. `batch` 왜 받아요?
**A**. API 설계시에 이미 `/members/batch`의 구조를 가져가고 있어서 일관성을 위해

그런데 근거가 많이 빈약하죠? 막상 `batch` 받아다가 쓰는 건 아니다 보니. 그래서 그냥 `memberId`만 받게 할라 하다가 문득 의견이 궁금해서 올려봤습니다.

2024-11-22 01:19 UTC, ekgns33 requested changes
고생하셨습니다😄😄

2024-11-22 01:19 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/controller/member/dtos/MemberUpdateInfo.java
> +  public void updateEntity(Member member) {
멤버의 수정을 Info가 담당하고 있네요! 이유가 있을까요?

2024-11-22 01:19 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
> +    public ResponseEntity<SuccessResponse> updateMembers(
배치의 유저를 모두 수정하는 api 같은데.. 이렇게할 이유가 있을까요? 너무 많은데이터를 한번에 수정하려하는 것 같아요. 성격도 다르구요

2024-11-22 01:19 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +      memberUpdateInfo.updateEntity(member);
엔티티의 수정을 벨류객체가 하네요? 의도가 궁금해요

2024-11-22 01:19 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +    return memberRepository.findAllByBatch(batch).stream().collect(toMap(Member::getId, identity()));
전체를 가져와서 필터링을 진행하는 군요. 입력의 key들은 list로 뽑을 수 있을텐데 sql에서 끝낼 수는 없었나요?? 반환된 레코드의 갯수와 비교하면 될 것 같아요. 루프를 불필요하게 많이 도는 것 같습니다

2024-11-22 01:19 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +  public List<Member> getMembers(String batch) {
네이밍을 getMembersInBatch 처럼 바꾸는건 어떨까요?

2024-11-22 03:33 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/controller/member/dtos/MemberUpdateInfo.java
> +  public void updateEntity(Member member) {
API 페이로드 양식에 따라서 업데이트 로직이 달라질거라고 생각했습니다. 가령 추후 batch는 업데이트 대상에서 제외될수도 있다고 생각했어요. Presentation Layer의 변경 전파를 줄이고 싶었습니다.

그런데 확실히 계층간 오염이 발생했다고 보는게 맞겠네요. 수정하겠습니다.

2024-11-24 09:50 UTC, ekgns33 approved these changes

2024-11-26 05:00 UTC, merged