Bp 25 implement user registration
gdsc-konkuk/platform-core pull request #6
Opened 2024-07-17 16:05 UTC by ekgns33

### 작업 목표
- 회원 가입을 위한 기능 개발

- 테스트 코드 작성

### 제한사항
- 이미 존재하는 유저가 회원가입을 시도할 시 실패하고 에러를 반환한다.

- 새로운 유저가 회원가입을 시도할 시 유저 정보를 저장한다.

- 회원 가입 시 유저의 비밀번호는 암호화하여 저장한다.

### 목표가 아닌것
프로필 이미지 저장은 현재 Task에서 구현하지 않는다.

- [x] 기능 개발
- [x] 테스트코드 작성

2024-07-18 04:58 UTC, zbqmgldjfh reviewed
지나가다 리뷰 남겨봅니다~~ 화이팅!!

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberRegisterRequest.java
> +@Builder
builder를 여기다 선언하면 다음과 같은 코드도 생성될것 같습니다.
```java
Member.builder()
		.memberId(request.getMemberId())
		.build();
```

또한 인자로 null도 전달 가능한 상황입니다. 방어적인 생성이 필요하다 봅니다.

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +	private boolean checkMemberAlreadyExist(String memberId) {
private 메서드는 public 메서드 보다 아래쪽에 나와야 합니다!!

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +	public SuccessResponse register(MemberRegisterRequest registerRequest) {
register 메서드는 SuccessResponse에 의존적이게 되었군요, 향후 다른 응답이 필요하면 해당 부분을 변경해야 할것 같은데요?
**Controller의 역할**을 조금더 생각해보시면 좋을것 같습니다.

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
> +	@PostMapping("")
("") 이부분 없어도 됩니다!

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
> +		return ResponseEntity.status(201).body(SuccessResponse.messageOnly());
201같은 상수를 직접 사용하기 보다는, HttpStatus 에 정의된 상수값을 사용하길 권장합니다.

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/global/controller/GlobalExceptionHandler.java
> +		log.error("UserAlreadyExistException Caught! [{}]", e.getLogMessage());
log.error("UserAlreadyExistException Caught! [{}]", e.getLogMessage(), e); 끝에 e도 인자로 추가하면 stack trace도 모두 출력됩니다. 추가적인 e를 위한 {}는 지정하지 않아도 되구요!

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/global/exceptions/ErrorCode.java
>  	INTERNAL_SERVER_ERROR("서버 오류입니다. 잠시후 재시도 해주세요", "[ERROR] : 예상치못한 에러 발생", 500),
이부분도 직접 500을 사용하기 보다는 HttpStatus 사용 권장

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/test/java/gdsc/konkuk/platformcore/application/member/MemberServiceTest.java
> +	void should_success_when_newMember_register() {
해당 class의 이름은 MemberServiceTest 인데, 
1) Transactional을 통해 데이터를 롤백한다는 것 -> Repository까지 확인하는 테스트 인것 같은데, 
2) 상단에 보면 Mock을 선언 -> Repository 는 가짜로 지정한 행동만 반환한다
인데, 둘중 뭘 의도한 테스트 인지 모르겠습니다.

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
> +	@MockBean
Mock과 MockBea의 차이점을 알고 있으실까요?? 확인해보시면 좋을것 같아요~!

2024-07-18 04:58 UTC, zbqmgldjfh commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +@Transactional(readOnly = true)
(readOnly = true)의 장점은 무엇일까요?

2024-07-18 08:06 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/global/exceptions/ErrorCode.java
>  	INTERNAL_SERVER_ERROR("서버 오류입니다. 잠시후 재시도 해주세요", "[ERROR] : 예상치못한 에러 발생", 500),
`ErrorCode.statusCode`는 HTTP Status가 아닌, front-end에서의 error handling을 위한 additional code입니다.

다만, 현재 `ErrorCode.logMessage`가 해당 역할을 홀로 완벽히 수행하고 있는 것으로 보이는데, 해당 property를 삭제에 대해서는 어떻게 생각하시나요?

2024-07-18 08:10 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
> +		return ResponseEntity.status(201).body(SuccessResponse.messageOnly());
동의합니다!

2024-07-18 08:43 UTC, goldentrash requested changes

2024-07-18 08:43 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +		Member member = Member.builder()
이 부분은 `MemberRegisterRequest`의 `toEntity` method와 역할이 겹치는것 같습니다.

`MemberRegisterRequest.toEntity`를 삭제하거나, 해당 method 내부로 로직을 옮기는 것에 대해 어떻게 생각하시나요?

2024-07-18 08:47 UTC, goldentrash requested changes
`/application` dir의 의미가 무엇일까요?

`controller`와 `domain`은 top-level에 위치하고, `service`는 `application` 아래에 위치시킨 이유가 궁금합니다. 일반적으로 `controller`와 `domain`에 비해 `service`의 규모가 비대해지는 경향이 있나요?

2024-07-18 09:30 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +	private boolean checkMemberAlreadyExist(String memberId) {
private를 아래로 내리겠습니다!

2024-07-18 09:32 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +	public SuccessResponse register(MemberRegisterRequest registerRequest) {
서비스단에서는 객체만 반환을 하고 프레젠테이션 레이어에서 응답객체를 만들어 반환하도록 하는것을 말씀하시나용?

2024-07-18 09:34 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
> +		return ResponseEntity.status(201).body(SuccessResponse.messageOnly());
매직넘버를 제거하고 `HttpStatus.Created`이런 정의된 상수를 사용하는 것을 말씀하시는걸까요?

2024-07-18 09:36 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/global/exceptions/ErrorCode.java
>  	INTERNAL_SERVER_ERROR("서버 오류입니다. 잠시후 재시도 해주세요", "[ERROR] : 예상치못한 에러 발생", 500),
맞습니다. 응답객체를 만들어주는 부분에서 http 응답코드를 정하면 enum에 정의할 필요가 없다고 생각해요. 어떻게 생각하시나요

2024-07-18 09:38 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/global/controller/GlobalExceptionHandler.java
> +		log.error("UserAlreadyExistException Caught! [{}]", e.getLogMessage());
그런 방법이 있군요! 적용해보겠습니다🤗

2024-07-18 09:39 UTC, ekgns33 commented on src/test/java/gdsc/konkuk/platformcore/application/member/MemberServiceTest.java
> +	void should_success_when_newMember_register() {
로컬에서 테스트할때 레포지토리를 살려놓은상태에서도 진행했는데 모킹하고나서도 그대로 놓은것 같습니다! 이 테스트에서는 서비스 레이어만 테스트하고자하여 삭제하겠습니다 😀

2024-07-18 09:51 UTC, ekgns33 commented on src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
> +	@MockBean
MockBean은 스프링애플리케이션 컨텍스트의 동일 유형의 빈을 대체하는 것으로 알고있습니다. 통합테스트나 외부의존성을 처리할때 사용한적이 있는데 이 테스트에서는 WebMvc를 사용하여 테스트를했기에 목빈을 사용했어요:)

2024-07-18 09:59 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +@Transactional(readOnly = true)
읽기 전용으로 트랜잭션을 설정하여 어느정도 성능의 이점을 가져갈 수 있습니다. 대표적으로 데이터 변경이 일어나지 않는것을 보장하므로 스냅샷을 저장하지 않죠(변경감지가 필요없어요). 다만 엔티티에 대해서 낙관적락을 사용하는 경우 쿼리한 데이터들의 수정을 리드온리에서 하는경우 일관성이 깨질 수 있습니다. 현재 우리 엔티티에는 낙관적 락을 적용하지 않았기 때문에 서비스 클래스에 넓은 범위로 적용했습니다. 위에서 언급한 내용은 데이터 수정과 관련된 메소드를 명세와 코드리뷰로 해결할 수 있다고 생각해요.

2024-07-18 10:02 UTC, ekgns33 commented
음 우선 레이어별로 디렉토리를 분리했어요! 그리고 말씀해주신 내용 관련해서는 서비스클래스 자체가 커질 수 있다고 생각해요. 그래서 애플리케이션레이어에서 조립의 역할을 하는 (일종의 파사드)와 서비스 레이어(실질적구현)을 나누고 싶었어요. 지금은 서비스가 하나뿐이라 크게 나뉘진 않네요

2024-07-18 10:03 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
> +		Member member = Member.builder()
toentity를 활용하는게 좋아보이네요. 그렇게 수정하겠습니다!

2024-07-19 04:55 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/member/exceptions/UserAlreadyExistException.java
`UserAlreadyExistException`의 필요를 잘 모르겠습니다.

사용되는 형태를 살펴보니 `UserAlreadyExistException.of(ErrorCode.USER_ALREADY_EXIST`의 형태입니다.
우리는 이미 `ErrorCode` Enum을 통해 Error의 유형을 구별하고 `logMessage`를 통한 메시지를 결정했습니다. 또한, `ErrorCode`는 `/global/excpetions`에 위치해서 codebase의 top-level에서 일괄 관리되고 있습니다. `application/member`라는 domain 단위로 나누어 관리하면서도 막상 `ErrorCode`를 담순 wrapping하기만 한다면 정말 필요한 객체일까요?

2024-07-19 05:09 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/exceptions/UserAlreadyExistException.java
음 에러코드에 의존하게된다는 말씀이군요. 하지만 에러코드의 경우 프로젝트 전역에서 공통으로 사용하는 값으로 로직이 존재하지않는 순수한 값만을 담고있는 클래스입니다. 의존이 생겨 에러코드를 사용하는 코드단에서 수정할일이 있을까요? 에러코드가 변해서 수정이 일어나야한다면 에러코드 자체를 바꾸는 경우만 생각나는데 이것은 로직의 변경으로 바라봐야하지 않을까요?

2024-07-19 05:14 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/exceptions/UserAlreadyExistException.java
예외클래스가 존재할 필요성에 대해서는 저는 이렇게 생각해요

- 1. 에러코드와 무관하게 에러추적할때 어떤 비즈니스로직에서 발생했는지 파악하기 용이하다.
- 2. 비즈니스 에러들을 하나로 묶어서 처리하면 에러코드 필드값으로 에러를 분류해야하는데 오히려 이게 복잡도를 높이지 않을까요? 에러코드는 같은데 예외의 이유가 다를 수 있을 것 같아요. 예외클래스 자체가 의미를 담고있다는 점에서 저는 만들었습니다

2024-07-19 05:28 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/member/exceptions/UserAlreadyExistException.java
`BusinessException.of(ErrorCode.User_ALREADY_EXIST)`의 형태로 사용해도 충분하지 않을까 싶었습니다.

아래는 `/global/controller/GlobalExceptionHandler`의 코드 일부분입니다.
```java
@ExceptionHandler(UserAlreadyExistException.class)
protected ResponseEntity<ErrorResponse> handleUserAlreadyExistException(final UserAlreadyExistException e) {
	log.error("UserAlreadyExistException Caught! [{}]", e.getLogMessage());
	final ErrorResponse response = ErrorResponse.of(e.getMessage(), e.getLogMessage());
	return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
}

@ExceptionHandler(BusinessException.class)
protected ResponseEntity<ErrorResponse> handleBusinessException(final BusinessException e) {
	log.error("BusinessException Caught! [{}]", e.getLogMessage());
	final ErrorResponse response = ErrorResponse.of(e.getMessage(), e.getLogMessage());
	return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
}
```

`BusinexxException`은 정의 및 사용 scope가 확실히 Global입니다. 그런데 `UserAlreadyExisitException`의 경우 정의는 Domain scope에서 이뤄지지만 사용은 Global scope까지 확장되고 있습니다. 앞으로 Domain이 계속 늘어날 것이고, Domain마다 각각의 Exception을 관리하게 될 것인데 이 모든 것들을 Global scope가 control해야 하는 구조는 관리에 어려움이 따를것같습니다.

그래서 떠오른 방법에 대한 @ekgns33의 의견이 궁금합니다!
1. `MemberErrorCode`를 `application/member`아래에 새로 정의합니다.
2. `UserAlreadyExistException` exception에 대한 controllerAddvice를 `/controller/member`로 옮깁니다.
3. `MemberControllerAdvice`에서 `BuisnessException`을 다시 throw합니다.

2024-07-19 06:32 UTC, ekgns33 commented on src/main/java/gdsc/konkuk/platformcore/application/member/exceptions/UserAlreadyExistException.java
1번으로 가는게 어떨까요

2024-07-19 06:52 UTC, goldentrash commented on src/main/java/gdsc/konkuk/platformcore/application/member/exceptions/UserAlreadyExistException.java
인터넷 오류였을까요...? 분명 전 하나의 답글을 보고 2번째 comment를 작성했는데 이제보니 2개네요???

말씀하신것처럼 `ErrorCode`만 사용하는것보다는 Class를 분기하는게 더 로직을 단순하게 만든다고 생각합니다.  제가 `BusinessException.of(ErrorCode.User_ALREADY_EXIST)`를 언급했던 이유는 ControllerAdvice에서 `BusinessException`과 `UserAlreadyExistException`의 처리에 약간의 log message를 제외한 나머지가 동일했기 때문입니다.

2번째 comment에서 작성한 떠오른 방법은 1, 2, 3 중에서 하나를 선택하자가 아닌 순서대로 전부라는 의미였는데, 지금 다시 읽어보니 뭔가뭔가인 느낌이 있네요. 해당 사항은 저도 조금 더 고민해 보겠습니다. 1번을 말씀하셨는데, 떠오른 좋은 구조가 있다면 편하신대로 re-factoring을 진행해주시면 감사합니다. 그런데 만약 저 3중에 하나를 골라야 한다고 생각하셨다면 전혀 아니니, 더 나은 구조가 없다면 현상 유지도 좋다고 생각합니다!

2024-07-20 13:12 UTC, goldentrash approved these changes

2024-07-20 13:22 UTC, merged